// <auto-generated />
namespace WebApplication7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class KeyCardChange11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KeyCardChange11));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041749110_KeyCardChange11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
